repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-toml
      - id: check-yaml
        files: \.yaml$
      - id: trailing-whitespace
        exclude: (migrations/|tests/).*
      - id: end-of-file-fixer
        exclude: (migrations/|tests/).*
      - id: check-added-large-files
        exclude: (migrations/|tests/).*
      - id: check-case-conflict
        exclude: (migrations/|tests/).*
      - id: check-merge-conflict
        exclude: (migrations/|tests/).*
      - id: check-docstring-first
        exclude: (migrations/|tests/).*

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: 2.2.1
    hooks:
      - id: pyproject-fmt

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: 1.3.1
    hooks:
      - id: tox-ini-fmt

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        exclude: (migrations/|tests/).*

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        args: [ "--config=pyproject.toml" ]
        exclude: (migrations/).*

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: [ "-c", "pyproject.toml", "-r", "." ]
        additional_dependencies: [ "bandit[toml]" ]
        exclude: (migrations/|tests/).*

  - repo: local
    hooks:
      - id: pytest
        name: Pytest
        entry: poetry run pytest -v
        language: system
        types: [ python ]
        stages: [ commit ]
        pass_filenames: false
        always_run: true

      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [ python ]
        require_serial: true
        args:
          - "-rn"
          - "-sn"
          - "--rcfile=pyproject.toml"
          - "--load-plugins=pylint_pytest"

        files: ^wait_for_db/
        exclude: (migrations/|tests/).*
