name: CI for Tests and Package Publishing

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install dependencies
        run: |
          uv pip install --system -e .
          uv pip install --system pre-commit tox codecov

      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files

      - name: Run tests with tox
        run: |
          tox

      - name: Stop on failure
        if: failure()
        run: exit 1

      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          flags: unittests
          fail_ci_if_error: true
          verbose: true

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: junit.xml
          report_type: test_results
          fail_ci_if_error: true

      - name: Upload HTML coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/

  publish:
    runs-on: ubuntu-latest
    needs: test

    if: github.event_name == 'release'  # Exécuter uniquement lors d'une release

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install build dependencies
        run: uv pip install --system build twine

      - name: Build package
        run: python -m build

      - name: Publish package
        run: twine upload dist/* --username __token__ --password ${{ secrets.PYPI_API_TOKEN }}
